# Generated by Django 5.2.3 on 2026-07-10 11:56

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='رزومه من', max_length=120, verbose_name='عنوان داخلی رزومه')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=180, unique=True, verbose_name='نشانی عمومی')),
                ('full_name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی')),
                ('job_title', models.CharField(blank=True, max_length=150, verbose_name='عنوان شغلی')),
                ('summary', models.TextField(blank=True, verbose_name='خلاصه حرفه\u200cای')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='تلفن')),
                ('location', models.CharField(blank=True, max_length=120, verbose_name='محل سکونت')),
                ('website', models.URLField(blank=True, verbose_name='وب\u200cسایت')),
                ('avatar', models.ImageField(blank=True, upload_to='resume_avatars/%Y/%m/', verbose_name='تصویر')),
                ('language', models.CharField(choices=[('fa', 'فارسی'), ('en', 'English')], default='fa', max_length=5, verbose_name='زبان رزومه')),
                ('template', models.CharField(choices=[('modern', 'مدرن'), ('minimal', 'مینیمال'), ('classic', 'کلاسیک')], default='modern', max_length=20, verbose_name='قالب')),
                ('accent_color', models.CharField(choices=[('#8b5cf6', 'بنفش'), ('#06b6d4', 'فیروزه\u200cای'), ('#2563eb', 'آبی'), ('#10b981', 'سبز'), ('#f97316', 'نارنجی'), ('#e11d48', 'قرمز'), ('#334155', 'خاکستری')], default='#8b5cf6', max_length=10, verbose_name='رنگ اصلی')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشرشده'), ('archived', 'بایگانی')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('visibility', models.CharField(choices=[('private', 'خصوصی'), ('unlisted', 'فقط با لینک'), ('public', 'عمومی')], default='private', max_length=20, verbose_name='دسترسی')),
                ('is_listed', models.BooleanField(default=False, verbose_name='نمایش در بخش رزومه\u200cها')),
                ('is_featured', models.BooleanField(default=False, verbose_name='رزومه ویژه صفحه اصلی')),
                ('show_email', models.BooleanField(default=True, verbose_name='نمایش ایمیل')),
                ('show_phone', models.BooleanField(default=False, verbose_name='نمایش تلفن')),
                ('views_count', models.PositiveIntegerField(default=0, editable=False)),
                ('downloads_count', models.PositiveIntegerField(default=0, editable=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=180, verbose_name='نام پروژه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('tech_stack', models.CharField(blank=True, max_length=250, verbose_name='فناوری\u200cها')),
                ('url', models.URLField(blank=True, verbose_name='لینک دمو')),
                ('github_url', models.URLField(blank=True, verbose_name='لینک کد')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='resumes.resume')),
            ],
            options={
                'ordering': ('position', 'created_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=80, verbose_name='زبان')),
                ('level', models.CharField(blank=True, max_length=50, verbose_name='سطح')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='resumes.resume')),
            ],
            options={
                'ordering': ('position', 'created_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(max_length=150, verbose_name='عنوان شغلی')),
                ('company', models.CharField(max_length=150, verbose_name='شرکت / مجموعه')),
                ('location', models.CharField(blank=True, max_length=120, verbose_name='محل')),
                ('start_date', models.CharField(blank=True, max_length=50, verbose_name='شروع')),
                ('end_date', models.CharField(blank=True, max_length=50, verbose_name='پایان')),
                ('is_current', models.BooleanField(default=False, verbose_name='هم\u200cاکنون مشغولم')),
                ('description', models.TextField(blank=True, verbose_name='شرح وظایف و دستاوردها')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='resumes.resume')),
            ],
            options={
                'ordering': ('position', 'created_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('degree', models.CharField(max_length=150, verbose_name='مقطع / مدرک')),
                ('field', models.CharField(blank=True, max_length=150, verbose_name='رشته')),
                ('institution', models.CharField(max_length=180, verbose_name='دانشگاه / موسسه')),
                ('location', models.CharField(blank=True, max_length=120, verbose_name='محل')),
                ('start_date', models.CharField(blank=True, max_length=50, verbose_name='شروع')),
                ('end_date', models.CharField(blank=True, max_length=50, verbose_name='پایان')),
                ('grade', models.CharField(blank=True, max_length=30, verbose_name='معدل')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='resumes.resume')),
            ],
            options={
                'ordering': ('position', 'created_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=180, verbose_name='عنوان مدرک')),
                ('issuer', models.CharField(blank=True, max_length=150, verbose_name='صادرکننده')),
                ('issue_date', models.CharField(blank=True, max_length=50, verbose_name='تاریخ')),
                ('credential_url', models.URLField(blank=True, verbose_name='لینک مدرک')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='resumes.resume')),
            ],
            options={
                'ordering': ('position', 'created_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, verbose_name='مهارت')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='دسته\u200cبندی')),
                ('level', models.CharField(choices=[('beginner', 'مقدماتی'), ('intermediate', 'متوسط'), ('advanced', 'پیشرفته'), ('expert', 'حرفه\u200cای')], default='intermediate', max_length=20, verbose_name='سطح')),
                ('percentage', models.PositiveSmallIntegerField(default=70, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد نمایشی')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='resumes.resume')),
            ],
            options={
                'ordering': ('position', 'created_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('platform', models.CharField(max_length=80, verbose_name='شبکه')),
                ('url', models.URLField(verbose_name='لینک')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='resumes.resume')),
            ],
            options={
                'ordering': ('position', 'created_at'),
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['status', 'visibility', 'is_listed'], name='resumes_res_status_d3fe39_idx'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['slug'], name='resumes_res_slug_f83f0a_idx'),
        ),
    ]
