# Generated by Django 5.2.3 on 2026-07-19 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_alter_certificate_issue_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='is_current',
            field=models.BooleanField(default=False, verbose_name='هم\u200cاکنون در حال تحصیل هستم'),
        ),
        migrations.AddField(
            model_name='experience',
            name='achievements',
            field=models.TextField(blank=True, help_text='هر وظیفه یا دستاورد را در یک خط جدا بنویس.', verbose_name='وظایف و دستاوردها'),
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.CharField(blank=True, max_length=150, verbose_name='کارفرما / درخواست\u200cکننده'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_date',
            field=models.CharField(blank=True, max_length=10, verbose_name='تاریخ پروژه'),
        ),
        migrations.AddField(
            model_name='resume',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='تلفن دوم'),
        ),
        migrations.AddField(
            model_name='resume',
            name='birth_date',
            field=models.CharField(blank=True, max_length=10, verbose_name='تاریخ تولد'),
        ),
        migrations.AddField(
            model_name='resume',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'مجرد'), ('married', 'متأهل'), ('other', 'سایر')], max_length=20, verbose_name='وضعیت تأهل'),
        ),
        migrations.AddField(
            model_name='resume',
            name='military_status',
            field=models.CharField(blank=True, choices=[('completed', 'پایان خدمت'), ('exempt', 'معافیت'), ('in_service', 'در حال خدمت'), ('not_applicable', 'مشمول نیست'), ('unset', 'ذکر نشود')], default='unset', max_length=20, verbose_name='وضعیت سربازی'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True, verbose_name='معرفی کوتاه این سابقه'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, verbose_name='شرح پروژه و دستاوردها'),
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=160, verbose_name='علاقه\u200cمندی')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='resumes.resume')),
            ],
            options={
                'ordering': ('position', 'created_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SoftSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=160, verbose_name='مهارت نرم')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soft_skills', to='resumes.resume')),
            ],
            options={
                'ordering': ('position', 'created_at'),
                'abstract': False,
            },
        ),
    ]
